---
all:
  children:
    source_environment:
      hosts:
        src_api_server:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
    destination_environment:
      hosts:
        dst_api_server:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
    isva_saas:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"