---
# Source Environment Variables
# Corporate Standard - Source API Configuration

# Source Tenant Configuration
src_tenant: "{{ lookup('env', 'SRC_TENANT') | default('https://labsso.verify.ibm.com', true) }}"
src_client_id: "{{ lookup('env', 'SRC_CLIENT_ID') | default('ab43937a-67e2-4438-9c9e-c460b9679a60', true) }}"
src_client_secret: "{{ lookup('env', 'SRC_CLIENT_SECRET') | default('46qzxKucUO', true) }}"

#src_tenant: "https://labsso.verify.ibm.com"
#src_client_id: ""
#src_client_secret: "46qzxKucUO"
# Source API Endpoints
src_token_url: "{{ src_tenant }}/oauth2/token"
src_applications_url: "{{ src_tenant }}/v1.0/applications"
src_attributes_url: "{{ src_tenant }}/v1.0/attributes"

# Source Environment Specific Settings
src_environment_name: "development"
src_region: "US-EAST"

# Made with Bob
